---
- apt_key:
    url: https://download.docker.com/linux/debian/gpg
    state: present
  become: true

- apt_repository:
    repo: deb https://download.docker.com/linux/debian buster stable
    state: present
  become: true

- name: install pip3 and git
  become: true
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - python3-pip
    - git
    - docker-ce
    - docker-compose

- name: Install Docker Libs For Python
  become: true
  pip:
    name: "{{ item }}"
  with_items:
    - docker
    - docker-compose
    - python-gitlab